trigger:
- master  
pool:
  vmImage: 'windows-latest'
variables:
  BuildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: 'src\JsonAutoService\*.csproj'
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'src\JsonAutoService\*.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
- task: NuGetCommand@2
  displayName: 'Push package to nuget.org'
  inputs:
    command: push
    packagesToPush: 'src\JsonAutoService\bin\Release\*.nupkg'
    nuGetFeedType: external
    publishFeedCredentials: nuget.org
- task: NuGetCommand@2
  displayName: 'Push package to internal feed'
  inputs:
    command: push
    packagesToPush: 'src\JsonAutoService\bin\Release\*.nupkg'
    publishVstsFeed: '056601d6-dfaa-4347-b739-d744df6a7c63'