# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master  
variables:
  buildConfiguration: 'Release'
pool:
  vmImage: 'windows-latest'

stages:
- stage: Build
  displayName: "Build project"
  jobs:
  - job: BuildJob
    displayName: "Build job"
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: restore
        projects: 'src\JsonAutoService\*.csproj'
    - task: DotNetCoreCLI@2
      displayName: 'dotnet publish'
      inputs:
        command: publish
        publishWebProjects: false
        projects: 'src\JsonAutoService\*.csproj'
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
- stage: Publish
  displayName: "Publish nuget"
  jobs:
  - job: PublishJob
    displayName: "Publish nuget to feeds"
    steps:
    - task: NuGetCommand@2
      displayName: 'Push package to nuget.org'
      inputs:
        command: push
        packagesToPush: 'src\JsonAutoService\bin\Release\*.nupkg'
        nuGetFeedType: external
        publishFeedCredentials: nuget.org
    - task: NuGetCommand@2
      displayName: 'Push package to internal feed'
      inputs:
        command: push
        packagesToPush: 'src\JsonAutoService\bin\Release\*.nupkg'
        publishVstsFeed: '056601d6-dfaa-4347-b739-d744df6a7c63'